# -*- coding: utf-8 -*-
# @Author: ZwEin
# @Date:   2016-08-08 11:46:11
# @Last Modified by:   ZwEin
# @Last Modified time: 2016-09-09 14:19:39


from vendor.crf_tokenizer import CrfTokenizer
from common import cleaner
from seed import seeds

DC_NODE_EXT_FEATURE_NAME_CONTENT = 'extracted_text'    # extracted_text
DC_NODE_EXT_FEATURE_NAME_POSTTIME = 'posttime'
DC_NODE_EXT_FEATURE_NAME_CITY = 'city'
DC_NODE_EXT_FEATURE_NAME_TEXT = 'text'
DC_NODE_EXT_FEATURE_NAME_REGION = 'region'
DC_NODE_EXT_FEATURE_NAME_TITLE = 'title'
DC_NODE_EXT_FEATURE_NAME_USERLOCATION = 'userlocation'
DC_NODE_EXT_FEATURE_NAME_PHONENUMBER = 'phonenumber'
DC_NODE_EXT_FEATURE_NAME_SID = 'sid'
DC_NODE_EXT_FEATURE_NAME_OTHERADS = 'otherads'
DC_NODE_EXT_FEATURE_NAME_AGE = 'age'
DC_NODE_EXT_FEATURE_NAME_DOCID = 'doc_id'

DC_NODE_EXT_FEATURE_NAME_EMAIL = 'email'
DC_NODE_EXT_FEATURE_NAME_DRUG_USE = 'drug_use'
DC_NODE_EXT_FEATURE_NAME_PRICE = 'price'
DC_NODE_EXT_FEATURE_NAME_LOCATION = 'location'
DC_NODE_EXT_FEATURE_NAME_PRICE_PER_HOUR = 'price_per_hour'
DC_NODE_EXT_FEATURE_NAME_BUSINESS_TYPE = 'business_type'
DC_NODE_EXT_FEATURE_NAME_URL = 'url'
DC_NODE_EXT_FEATURE_NAME_SERVICES = 'services'
DC_NODE_EXT_FEATURE_NAME_GENDER = 'gender'
DC_NODE_EXT_FEATURE_NAME_PHONE = 'phone'

DC_NODE_EXT_FEATURES = [
    DC_NODE_EXT_FEATURE_NAME_LOCATION,
    DC_NODE_EXT_FEATURE_NAME_URL,
    DC_NODE_EXT_FEATURE_NAME_GENDER,
    DC_NODE_EXT_FEATURE_NAME_PHONE,
    DC_NODE_EXT_FEATURE_NAME_AGE
]

DC_NODE_FEATURES = DC_NODE_EXT_FEATURES + sorted(seeds)
# DC_NODE_FEATURES = sorted(seeds)
# print DC_NODE_FEATURES
class Node(object):

    def __init__(self, content, sid=None, label=None, **attrs):
        self._content = content.encode('utf-8') if content else None
        self._sid = sid
        self._label = label
        self._seeds = seeds
        self._attrs = attrs
        self._features = self.load_features(content)
        self._vector = self.generate_vector()


        # print self._features        
        # for attr in sorted(self.attrs.keys()):
        #     print attr, ':', attrs[attr]

    #################################################
    # Clean Content 
    #################################################

    def clean(self, text):
        if not text:
            return ''
        # text = text.encode('ascii', 'ignore')
        text = cleaner.clean_text(text)
        text = text.encode('utf-8')
        # text = unicode(text, 'utf-8')
        # try:
        #     text = text.encode('ascii', 'ignore')
        # except:
        #     text = text.decode('utf-8', 'ignore')
        t = CrfTokenizer()
        t.setRecognizeHtmlEntities(True)
        t.setRecognizeHtmlTags(True)
        t.setSkipHtmlTags(True)
        tokens = t.tokenize(text)

        tokens = [cleaner.clean_token(token) for token in tokens]
        tokens = [_ for _ in set(tokens) if _]

        try:
            str(' '.join(tokens))
        except:
            print text.encode('utf-8')
            print tokens

        return str(' '.join(tokens)).decode('utf-8', 'ignore').encode('ascii', 'ignore')

    #################################################
    # Load Feature
    #################################################
    
    def load_seed_features(self, content):
        if not content:
            return {}
        ans = {}
        content = self.clean(content)
        seed_words = seeds.keys()
        seeds_size = len(seed_words)
        # seed_words.sort()
        tokens = content.split(' ')
        for i in range(seeds_size):
            if seed_words[i] in tokens:
                ans.setdefault(seed_words[i], str(1.0 * float(seeds[seed_words[i]])))
        return ans

    def load_ext_features(self, content=None):
        def raw2json(raw):
            import ast
            if not raw:
                return []
            try:
                return ast.literal_eval(raw)
            except:
                return raw

        def __ac_func_location(raw):
            if raw:
                return 1.
            return 0.
        def __ac_func_email(raw):
            if raw:
                return float(len(raw))
            return 0.
        def __ac_func_drug_use(raw):
            if raw:
                return 1.
            return 0.
        def __ac_func_price(raw):
            if raw:
                return float(len(raw))
            return 0.
        def __ac_func_price_per_hour(raw):
            if raw:
                # return raw
                # print raw
                return float(len(raw))
            return 0.
        def __ac_func_business_type(raw):
            if raw:
                return float(len(raw))
            return 0.
        def __ac_func_url(raw):
            if raw:
                return 1.
            return 0.
        def __ac_func_services(raw):
            if raw:
                return float(len(raw))
            return 0.
        def __ac_func_gender(raw):
            if raw:
                for val in raw:
                    if val == 'female':
                        return 1.
            return 0.
        def __ac_func_phone(raw):
            if raw:
                return float(len(raw))
            return 0.
        def __ac_func_age(raw):
            if raw:
                return float(len(raw))
            return 0.

        attr_content_funcs = {
            'location': __ac_func_location,
            'email': __ac_func_email,
            'drug_use': __ac_func_drug_use, 
            'price': __ac_func_price, 
            'price_per_hour': __ac_func_price_per_hour, 
            'business_type': __ac_func_business_type, 
            'url': __ac_func_url, 
            'services': __ac_func_services, 
            'gender': __ac_func_gender, 
            'phone': __ac_func_phone, 
            'age': __ac_func_age,
            'special_symbol': lambda x: x
        }

        if self._attrs:
            # print self._attrs
            ans = {}
            for (attr_name, attr_value) in self._attrs.iteritems():
                # print attr_value, attr_value
                if attr_value and attr_value != '':
                    ans.setdefault(attr_name, attr_content_funcs[attr_name](raw2json(attr_value)))
            # ans.setdefault('unicode_symbol', load_unicode_symbol(content))
            return ans
        return {}

    def load_features(self, content):
        return dict(self.load_seed_features(content).items() + self.load_ext_features(content).items())

    #################################################
    # Transformat
    #################################################
    
    def generate_vector(self):
        features = DC_NODE_FEATURES
        feature_size = len(features)
        if not self._features:
            return ' '.join(['0'] * feature_size)
        vector = ['0'] * feature_size
        for i in range(feature_size):
            if features[i].lower() in self._features:
                vector[i] = str(1.0 * float(self._features[features[i]]))
        return ' '.join(vector)

               




if __name__ == '__main__':
    contents = [
    "      Publicado:      domingo, 3 de julio de 2016, 1:38 PM                                                                         Has encontrado el lugar donde una masajista te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000                           Edad de la persona que public el anuncio: 21              Ubicacin:          Heredia Taco Bell, San Francisco            Identificacin de la publicacin: 2899225 costarica          Otros anuncios de este usuario:         DOMINGO SENSUAL   Atrevida   Es  KIRA   71857376 - Costa Rica anuncios clasificados erticos y para adultos - erticos - backpage.com Has encontrado el lugar donde una masajista te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000 DOMINGO SENSUAL   Atrevida   Es KIRA   71857376 - 21", 
    "whitehouse disfruta en un lugar seguro y discreto full privacidad 70791261 / 70501012 - 23 whitehouse disfruta en un lugar seguro y discreto full privacidad  70791261 / 70501012 - Costa Rica anuncios clasificados erticos y para adultos - erticos - backpage.com Somos varias chicas dispuestas a complacer todas tus fantasas       Publicado:      sbado, 9 de julio de 2016, 12:17 PM                                                                         Somos varias chicas dispuestas a complacer todas tus fantasas                           Edad de la persona que public el anuncio: 23              Ubicacin:          alajuela montecillos            Identificacin de la publicacin: 3204126 costarica          Otros anuncios de este usuario:        ", 
    "Visiting: Treat Yourself to the Luxury of Two Experienced Goddesses Sharing Their Gifts - 37 Visiting: Treat Yourself to the Luxury of Two Experienced Goddesses Sharing Their Gifts - Boston body rubs - backpage.com                                                             Ajna & Maya embody tantric intuition & deep integrity.  With over 20 yrs. of experience, we bring healing, relaxation & bliss to every seeker.  We invite you to experience the power & pleasure of 4 skilled hands & 2 generous hearts for unparalleled sensual touch!  Visiting 6/27 - 7/2.    Read Ajna's ad below, and then call her if you have questions or are ready to schedule this uniquely luxurious experience...   http://seattle.backpage.com/BodyRubs/exceptional-touch-and-tantric-training/790465                Location:          Boston, Historic Downtown Boston, Fanueil Hall           Ajna & Maya embody tantric intuition & deep integrity. With over 20 yrs. of experience, we bring healing, relaxation & bliss to every seeker. We invite you to experience the power & pleasure of 4 skilled hands & 2 generous hearts for unparalleled sensual touch! Visiting 6/27 - 7/2. Read Ajna's ad below, and then call her if you have questions or are ready to schedule this uniquely luxurious experience... http://seattle.backpage.com/BodyRubs/exceptional-touch-and-tantric-training/790465", 
    "100% Real Pictures Open military and veteran 15% off parking in white stalls only 808-206-4393  .  Call or text808-206-4393 $60/1h house fee. HANABI SPAReal pictures SweetOpen military and veteran 15% off - 24       Posted:      Saturday, July 2, 2016 12:49 PM                                                                         100% Real Pictures  Open military and veteran 15% off  parking in white stalls only  808-206-4393   .  Call or text808-206-4393 $60/1h house fee.                           Poster's age: 24              Location:          23 S vineyard Blvd. #201, Honolulu (Oahu)            Post ID: 6048613 hawaii          Other ads by this user:         HANABI SPAReal pictures SweetOpen military and veteran 15% off - Hawaii body rubs - backpage.com", 
    "      Posted:      Monday, July 11, 2016 8:33 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Hempstead, Islip, Long Island, Sunrise Hwy / Route 27            Post ID: 82768326 longisland          Other ads by this user:         Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939  $40 Monday Madness Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - Long Island body rubs - backpage.com  $40 Monday Madness Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - 21", 
    "Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939       Posted:      Tuesday, June 28, 2016 10:36 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Brookhaven, Glen Cove, Hempstead, Huntington, Islip, Long Island, North Hempstead, Oyster Bay, Smithtown, Sunrise Hwy / Route 27            Post ID: 81995194 longisland          Other ads by this user:          $40 Tasty Tuesday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - 21  $40 Tasty Tuesday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - Long Island body rubs - backpage.com", 
    "The Professional's Choice - 43       Posted:      Sunday, July 3, 2016 2:50 PM                                                                         Ever wonder what true relaxation and a pleasnt experience is like? Don't wait a second longer! Clear your mind, leave refreshed, focused and relieved of everyday stress/this is the hour of the true gent who wants nothing but the best. Please be over age 40 and very respectful, slight screening required for all.                           Poster's age: 43              Location:          Beautiful North Office, Loveland, Boulder, Denver, Ft Collins            Post ID: 24282181 denver           The Professional's Choice - Denver body rubs - backpage.com Ever wonder what true relaxation and a pleasnt experience is like? Don't wait a second longer! Clear your mind, leave refreshed, focused and relieved of everyday stress/this is the hour of the true gent who wants nothing but the best. Please be over age 40 and very respectful, slight screening required for all.", 
    "10$OFF TODAY Pretty And young Asia girls! - 35 Try our NEW GIRL we will not let you down Deep Tissue Light Touch Hot stone essential oil WE ACCEPT CASH &CREDIT CARD TABLE MASSAGE 30min:$40 60min:$60 90min:$90 120min:$120 FUTON MASSAGE 30min:$60 60min:$70 90min:$110 120min$130 Four Hands---$130 Open 7days a week 10:00-10:00 Monday--Saturday 10:00-9:30 Saturday Call952-934-3671 15762 Venture Lane Eden Prairie MN,55344 10$OFF TODAY Pretty And young Asia girls! - Minneapolis / St. Paul body rubs - backpage.com       Posted:      Friday, July 1, 2016 6:47 PM                                                                         Try our NEW GIRL  we will not let you down    Deep Tissue   Light Touch   Hot stone   essential oil    WE ACCEPT CASH &CREDIT CARD      TABLE MASSAGE    30min:$40   60min:$60  90min:$90  120min:$120   FUTON MASSAGE    30min:$60  60min:$70  90min:$110  120min$130    Four Hands---$130   Open 7days a week  10:00-10:00 Monday--Saturday   10:00-9:30 Saturday    Call952-934-3671   15762 Venture Lane Eden Prairie MN,55344     Poster's age: 35              Location:          15762 venture lane Eden prairie MN 55344, Minneapolis / St. paul            Post ID: 17921365 minneapolis          ", 
    "Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939       Posted:      Wednesday, June 29, 2016 7:47 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Brookhaven, Glen Cove, Hempstead, Huntington, Islip, Long Island, North Hempstead, Oyster Bay, Smithtown, Sunrise Hwy / Route 27            Post ID: 82055071 longisland          Other ads by this user:          $40 Wacky Wednesday Special !Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - Long Island body rubs - backpage.com  $40 Wacky Wednesday Special !Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - 21", 
    "      Posted:      Saturday, July 9, 2016 12:50 PM                                                                         24HrS  Body to Body Couples  Fetishes Unrushed Sessions  2-GIRL-Sessions Private Parking     Directions;South on Powerline right at Ihop then 1st left into shopping plaza suite 1415 next to Dunkin Donuts behind Checkers!!!                           Poster's age: 21              Location:          1415 South Powerline Road,Pompano, West Palm Beach            Post ID: 32553828 westpalmbeach           24HrS  Body to Body Couples  Fetishes Unrushed Sessions 2-GIRL-Sessions Private Parking Directions;South on Powerline right at Ihop then 1st left into shopping plaza suite 1415 next to Dunkin Donuts behind Checkers!!! #1 Voted BEST BoDyrUbS \"  SPA MAGIC   \"JENNY\" & \"CANDY\" &\" SARAH\" (954)793-7155 - West Palm Beach body rubs - backpage.com #1 Voted BEST BoDyrUbS \"  SPA MAGIC   \"JENNY\" & \"CANDY\" &\" SARAH\" (954)793-7155 - 21", 
    "      Posted:      Sunday, July 3, 2016 12:36 PM                                                                         Ever wonder what true relaxation and a pleasnt experience is like? Don't wait a second longer! Clear your mind, leave refreshed, focused and relieved of everyday stress/this is the hour of the true gent who wants nothing but the best. Please be over age 40 and very respectful, slight screening required for all.                           Poster's age: 43              Location:          Beautiful North Office, Loveland, Boulder, Denver, Ft Collins            Post ID: 24282181 fortcollins           The Professional's Choice - 43 Ever wonder what true relaxation and a pleasnt experience is like? Don't wait a second longer! Clear your mind, leave refreshed, focused and relieved of everyday stress/this is the hour of the true gent who wants nothing but the best. Please be over age 40 and very respectful, slight screening required for all. The Professional's Choice - Fort Collins body rubs - backpage.com", 
    "      Posted:      Saturday, June 25, 2016 10:57 PM                                                               Looking for beautiful woman 18-35 interested in the adult industry.                                      Location:          Austin, East Bay, Monterey, North Bay, San Francisco, San Jose / South Bay            Post ID: 36475547 sanjose           Beautiful girls wanted free trip to Austin - San Jose model, actor, auditionsand casting calls - backpage.com Beautiful girls wanted free trip to Austin", 
    "bye guys! ve back next week!  - 28       Posted:      Thursday, June 16, 2016 2:52 AM                                                                         be back next week!                           Poster's age: 28              Location:          Rockville, Gaithersburg, Bethesda, Southern Maryland            Post ID: 20832226 washingtondc          Other ads by this user:         be back next week! bye guys! ve back next week!  - Washington body rubs - backpage.com", 
    "24hr 718-559-7060HOT BODY2BODY SLIDING   NEW LINEUP 4 U - Queens body rubs - backpage.com 24hr 718-559-7060HOT BODY2BODY SLIDING   NEW LINEUP 4 U - 23       Posted:      Sunday, July 10, 2016 4:16 PM                The best bodyru and nuru massage from our hottest Chinese  718-559-7060) 24 hours on     Poster's age: 23              Location:          35th Ave & Prince St, Flushing, Flushing, Queens            Post ID: 61713056 queens           The best bodyru and nuru massage from our hottest Chinese 718-559-7060) 24 hours on", 
    "Tues 1-8pm - Louisville body rubs - backpage.com What is Reiki? Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy. Tues 1-8pm - 99       Posted:      Saturday, July 2, 2016 8:42 AM                                                                         What is Reiki?      Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy.                           Poster's age: 99              Location:          Bardstown/Taylorsville Rd, Louisville            Post ID: 9231358 louisville          ", 
    "Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939  $40 Thirsty Thursday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call $40  - 21       Posted:      Thursday, June 30, 2016 3:11 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Brookhaven, Glen Cove, Hempstead, Huntington, Islip, Long Island, North Hempstead, Oyster Bay, Smithtown, Sunrise Hwy / Route 27            Post ID: 82107117 longisland          Other ads by this user:          $40 Thirsty Thursday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call $40  - Long Island body rubs - backpage.com", 
    "Sensual Soothing Bodywork - 55 Sensual Soothing Bodywork - Ocala body rubs - backpage.com       Posted:      Wednesday, June 22, 2016 9:42 AM                                                                         It's Hot! Cool Down With Sensual Soothing Touch! Email:  sendinfo2zen@gmail.com     Poster's age: 55              Location:          Ocala, Wildwood S Ocala Lady Lake Villages Area            Post ID: 9455516 ocala           It's Hot!Cool Down With Sensual Soothing Touch!Email: sendinfo2zen@gmail.com", 
    "      Posted:      Tuesday, July 12, 2016 3:28 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Hempstead, Islip, Long Island, Sunrise Hwy / Route 27            Post ID: 82809306 longisland          Other ads by this user:         Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939  $40 Tasty Tuesday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - 21  $40 Tasty Tuesday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - Long Island body rubs - backpage.com", 
    "      Posted:      Friday, July 8, 2016 1:27 PM                                                                         =======Li Beauty & Spa=====  Dear New Yorkers:  you have to know where your pointless.  If you want really Massage with  romantic touch,There is your best choice.  *Table shower*Swedish * Shiatsu * Deep tissue *Body scrub**Table shower?    II.(( Downtown =BEAVER ST))646_490_6850((CLOSE BROADWAY)) ((OPEN 10:00AM-8:30pM)) SAT & SUN =OPEN 11:00AM-7:00pm .                           Poster's age: 28              Location:          beaver st, Downtown, Manhattan            Post ID: 42844768 manhattan          Other ads by this user:         =======Li Beauty & Spa===== Dear New Yorkers: you have to know where your pointless. If you want really Massage with romantic touch,There is your best choice. *Table shower*Swedish * Shiatsu * Deep tissue *Body scrub**Table shower? II.(( Downtown =BEAVER ST))646_490_6850((CLOSE BROADWAY)) ((OPEN 10:00AM-8:30pM)) SAT & SUN =OPEN 11:00AM-7:00pm . (Downtown)(what's important on your bodysoft touch &best deep tissues in NY NO.1You will be back - Manhattan body rubs - backpage.com (Downtown)(what's important on your bodysoft touch &best deep tissues in NY NO.1You will be back - 28", 
    "Has encontrado el lugar donde una masajista te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000   Antojado de una Nuevita   Esta ANGELA  71857376 - Costa Rica anuncios clasificados erticos y para adultos - erticos - backpage.com       Publicado:      martes, 21 de junio de 2016, 11:24 AM                                                                         Has encontrado el lugar donde una masajista te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000                           Edad de la persona que public el anuncio: 24              Ubicacin:          FOTOS NUEVAS **.            Identificacin de la publicacin: 2900421 costarica          Otros anuncios de este usuario:           Antojado de una Nuevita   Esta ANGELA 71857376 - 24", 
    "El Masaje Ertico Descubre Para Ti Nuevas Formas De Estimular Tu Cuerpo, Desde Perspectivas Distintas Y Novedosas. Te Ofrecemos Una Exclusiva Carta De Masajes Cuyo Fin Primordial Es Llegar A Niveles Mucho Ms Profundos Y Ayudar A Fluir De Manera Ms Positiva Para Un ptimo Rendimiento En Tu Vida. Vistanos a la alt cdra. 18 de arenales c 2 canevaro y Llmanos al 967822424       Publicado:      sbado, 9 de julio de 2016, 6:21 PM                                                                         El Masaje Ertico Descubre Para Ti Nuevas Formas De Estimular Tu Cuerpo, Desde Perspectivas Distintas Y Novedosas.  Te Ofrecemos Una Exclusiva Carta De Masajes Cuyo Fin Primordial Es Llegar A Niveles Mucho Ms Profundos Y Ayudar A Fluir De Manera Ms Positiva Para Un ptimo Rendimiento En Tu Vida. Vistanos a la alt cdra. 18 de arenales c 2 canevaro y Llmanos al 967822424                           Edad de la persona que public el anuncio: 22              Ubicacin:          18 de arenales, Lima            Identificacin de la publicacin: 4064102 lima          Otros anuncios de este usuario:         MASAJES suaves full relajantes en lince - 22 MASAJES suaves full relajantes en lince - Lima anuncios clasificados erticos y para adultos - erticos - backpage.com", 
    "Soy  SHARLIN   15MIL asaje  % TANTRICO *    71857376  - Costa Rica anuncios clasificados erticos y para adultos - erticos - backpage.com Has encontrado el lugar donde una masajista te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000       Publicado:      mircoles, 29 de junio de 2016, 7:41 PM                                                                         Has encontrado el lugar donde una masajista te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000                           Edad de la persona que public el anuncio: 26              Ubicacin:          Heredia Taco Bell, San Francisco0T!            Identificacin de la publicacin: 3048001 costarica          Otros anuncios de este usuario:         Soy SHARLIN  15MIL asaje  % TANTRICO *    71857376  - 26", 
    "Saturday 12-4 still avbl booking fast! - 99 What is Reiki? Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy. Saturday 12-4 still avbl booking fast! - Kentucky body rubs - backpage.com       Posted:      Friday, July 8, 2016 12:03 PM                                                                         What is Reiki?      Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy.                           Poster's age: 99              Location:          Bardstown/Taylorsville Rd, Louisville            Post ID: 9231358 kentucky          ", 
    "      Posted:      Wednesday, 13 July 2016, 19:16               Description        .  , ,  ,  ,  .   .    : 2000 .     Tel:  8-981-765-29-65                Location:          Sankt-Peterburg            Post ID: 2960882 sankt-peterburg                 - Sankt-peterburg body rubs - backpage.com", 
    "      Posted:      Thursday, June 23, 2016 5:27 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Brookhaven, Glen Cove, Hempstead, Huntington, Islip, Long Island, North Hempstead, Oyster Bay, Smithtown, Sunrise Hwy / Route 27            Post ID: 81655759 newyork          Other ads by this user:         Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939  $40 Thirsty Thursday Special !!Grand Opening! NEW Brazilian & Latina Dolls Await!! Call $40  - New York body rubs - backpage.com  $40 Thirsty Thursday Special !!Grand Opening! NEW Brazilian & Latina Dolls Await!! Call $40  - 21", 
    "Ariel Capri, Elite and Independent Courtesan for the Discerning Gentleman!           This site contains adult material. If you are under 21 years of    age or it is illegal to view adult material in your community, you must leave now. By   continuing further into this site you release the owner and creator of this site of    all liability. If you decide to continue, you do so at your own risk and accept full   responsibility for your actions.        2016 Copyright DivaDivine.net, All Rights Reserved - Site Design by     4Front Web Design      ", 
    "Wed 12:30-5:30pm - 99       Posted:      Wednesday, July 6, 2016 8:37 AM                                                                         What is Reiki?      Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy.                           Poster's age: 99              Location:          Bardstown/Taylorsville Rd, Louisville            Post ID: 9231358 kentucky           What is Reiki? Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy. Wed 12:30-5:30pm - Kentucky body rubs - backpage.com", 
    "https://twitter.com/vip_masseuse1 I offer the best in the art of sensual and therapeutic massage (Shower Available) Professional deep tissue massage 1hour session $80.00 Bikini massage $150.00hr Mutual touch bodyslide massage $250.00hr Vip massage $400.00hr       Posted:      Thursday, June 23, 2016 3:53 AM                I offer the best in the art of sensual and therapeutic massage (Shower Available)   Professional deep tissue massage 1hour session $80.00   Bikini massage $150.00hr  Mutual touch bodyslide massage $250.00hr   Vip massage $400.00hr                           Poster's age: 36              Location:          Toledo,   Visiting private Hotel suite            Post ID: 26700688 ohio             Visiting Vip Sensual   Masseuse... 917-600-5591  - Ohio body rubs - backpage.com   Visiting Vip Sensual  Masseuse... 917-600-5591  - 36", 
    "We have many New pretty staffs and well-trained masseuses whom surely know how to give excellent massage. Deep tissue Massage -30min- $50/60min-$70( Free Table shower) -90min-$100(Free Scrub& Table shower) VIP Special-Exfoliate Full Body Scrub & Massage -Buff your skin into super) -Smooth shape with our exfoliaing scru) -1HR-$80,90min-$100,2HR-$120 702-432-7300 ~*IRIS DAY SPA 6985 W SAHARA #108 LAS VEGAS, NV89117 (across BMW on W Sahara )       Posted:      Saturday, July 2, 2016 10:34 AM                 We have many New pretty staffs and well-trained masseuses whom surely   know how to give excellent massage.     Deep tissue Massage   -30min- $50/60min-$70( Free Table shower)   -90min-$100(Free Scrub& Table shower)     VIP  Special-Exfoliate Full Body Scrub & Massage   -Buff your skin into super)   -Smooth shape with our exfoliaing scru)    -1HR-$80,90min-$100,2HR-$120   702-432-7300       ~*IRIS DAY SPA   6985 W SAHARA #108   LAS VEGAS, NV89117    (across BMW on  W Sahara )                           Poster's age: 27              Location:          6985 w sahara #108  Las vegas, NV89117, East, Las Vegas            Post ID: 9428277 nevada          Other ads by this user:         (I_R_I_S )  (D_A_Y_)  (S_P_A_) -( Vip90min Special-$100) Free Table Shower/Scrub - Nevada body rubs - backpage.com (I_R_I_S )  (D_A_Y_)  (S_P_A_) -( Vip90min Special-$100) Free Table Shower/Scrub - 27", 
    "El Masaje Ertico Descubre Para Ti Nuevas Formas De Estimular Tu Cuerpo, Desde Perspectivas Distintas Y Novedosas. Te Ofrecemos Una Exclusiva Carta De Masajes Cuyo Fin Primordial Es Llegar A Niveles Mucho Ms Profundos Y Ayudar A Fluir De Manera Ms Positiva Para Un ptimo Rendimiento En Tu Vida. Vistanos a la alt cdra. 18 de arenales c 2 canevaro y Llmanos al 967822424       Publicado:      sbado, 9 de julio de 2016, 6:21 PM                                                                         El Masaje Ertico Descubre Para Ti Nuevas Formas De Estimular Tu Cuerpo, Desde Perspectivas Distintas Y Novedosas.  Te Ofrecemos Una Exclusiva Carta De Masajes Cuyo Fin Primordial Es Llegar A Niveles Mucho Ms Profundos Y Ayudar A Fluir De Manera Ms Positiva Para Un ptimo Rendimiento En Tu Vida. Vistanos a la alt cdra. 18 de arenales c 2 canevaro y Llmanos al 967822424                           Edad de la persona que public el anuncio: 22              Ubicacin:          18 de arenales, Lima            Identificacin de la publicacin: 4064104 lima          Otros anuncios de este usuario:         MASAJES suaves full relajantes en lince - 22 MASAJES suaves full relajantes en lince - Lima anuncios clasificados erticos y para adultos - erticos - backpage.com", 
    " $30/60min 10 Experienced Young GirlsLot of OIL BodyToBody 6468817688 - 19 $30/30 min $40/60min LOWEST PRICE BEST SERVICE Girls Under 25  We show ID Open minded CRAZY in B Skillful Work you've never seen in other places 10 GIRLs everyday You can choose from Nuru Hot & Cold 69 Swirling Dragon FOUR HANDS Private Luxury Rooms Discreet and Private FREE ACTUAL PARKING LOT CALL 646-881-7688       Posted:      Wednesday, June 29, 2016 7:19 PM                                                                         $30/30 min $40/60min  LOWEST PRICE BEST SERVICE  Girls Under 25  We show ID  Open minded CRAZY in B  Skillful Work you've never seen in other places  10 GIRLs everyday You can choose from  Nuru  Hot & Cold  69  Swirling Dragon   FOUR HANDS   Private Luxury Rooms  Discreet and Private         FREE ACTUAL PARKING LOT      CALL 646-881-7688                           Poster's age: 19              Location:          *College Point / 40th rd , Flushing, Long Beach, Long Island, Queens            Post ID: 76260146 longisland            $30/60min 10 Experienced Young GirlsLot of OIL BodyToBody 6468817688 - Long Island body rubs - backpage.com", 
    "    Stop Searching, Call  Us !!! All for You!!!  - Queens body rubs - backpage.com       Posted:      Friday, June 24, 2016 3:37 PM                                         YOU will GET                                     PRIVATE & CLEAN your ROOM                                Oil & Milk Bathe                                 Soothed BODY WORK                                 NEVER RUSHED                                 SWEET TALK with Friendly STAFF                                  EASY PARKING                          OPEN:  7 DAYs                                 Poster's age: 20              Location:          159th St. Northern Blvd, Flushing, Queens            Post ID: 81727306 queens            Stop Searching, Call Us !!! All for You!!!  - 20  YOU will GET   PRIVATE & CLEAN your ROOM  Oil & Milk Bathe  Soothed BODY WORK  NEVER RUSHED  SWEET TALK with Friendly STAFF  EASY PARKING  OPEN: 7 DAYs ", 
    "Abby's all girl staff 861 North military trail West palm beach $160 half hour $260 hour No tipping For all the fun you can handle Here Tiny Layla - 23 Tiny Layla - West Palm Beach body rubs - backpage.com         Posted:      Monday, June 27, 2016 8:20 PM         Reply                                                                     Abby's all girl staff  861 North military trail  West palm beach  $160 half hour  $260 hour  No tipping  For all the fun you can handle  Here                           Poster's age: 23              Location:          861 north military trail, West Palm Beach            Post ID: 38323207 westpalmbeach          Other ads by this user:            ", 
    "Beautiful girls wanted free trip to Austin - New York model, actor, auditionsand casting calls - backpage.com Beautiful girls wanted free trip to Austin       Posted:      Saturday, June 25, 2016 10:57 PM                                                               Looking for beautiful woman 18-35 interested in the adult industry.                                      Location:          Austin, Brooklyn, Long Island, Manhattan, Westchester            Post ID: 81826252 newyork          ", 
    "Here you will find 10 contact ads regarding the search Thai massage in Kolkata on Locanto Dating Thai massage Kolkata  contact ads Locanto Dating   Access this feature by upgrading to a Premium Account!          ", 
    "      Posted:      Monday, July 11, 2016 2:15 PM                                                                         Enjoy our full body massage ,                           Poster's age: 22              Location:          2249 W, Anaheim, Orange County            Post ID: 73623022 orangecounty           Enjoy our full body massage , Best Massage ( La Habra ) ( 2249 W , Whittier Blvd near Beach Blvd )- 22 - Orange County body rubs - backpage.com Best Massage ( La Habra ) ( 2249 W , Whittier Blvd near Beach Blvd )- 22 - 22", 
    "10$OFF TODAY Pretty And young Asia girls! - 35       Posted:      Friday, July 1, 2016 6:47 PM                                                                         Try our NEW GIRL  we will not let you down    Deep Tissue   Light Touch   Hot stone   essential oil    WE ACCEPT CASH &CREDIT CARD      TABLE MASSAGE    30min:$40   60min:$60  90min:$90  120min:$120   FUTON MASSAGE    30min:$60  60min:$70  90min:$110  120min$130    Four Hands---$130   Open 7days a week  10:00-10:00 Monday--Saturday   10:00-9:30 Saturday    Call952-934-3671   15762 Venture Lane Eden Prairie MN,55344     Poster's age: 35              Location:          15762 venture lane Eden prairie MN 55344, Minneapolis / St. paul            Post ID: 17921365 minnesota           Try our NEW GIRL we will not let you down Deep Tissue Light Touch Hot stone essential oil WE ACCEPT CASH &CREDIT CARD TABLE MASSAGE 30min:$40 60min:$60 90min:$90 120min:$120 FUTON MASSAGE 30min:$60 60min:$70 90min:$110 120min$130 Four Hands---$130 Open 7days a week 10:00-10:00 Monday--Saturday 10:00-9:30 Saturday Call952-934-3671 15762 Venture Lane Eden Prairie MN,55344 10$OFF TODAY Pretty And young Asia girls! - Minnesota body rubs - backpage.com", 
    "Gorgeous young Asian Ladies guarantee 626-37169574 hands & B to B  Near Acadia 10 FWY - 28       Posted:      Monday, July 4, 2016 2:09 PM                                                                         *WE have many gorgeous n young ladies are waiting for you     *Quite, clean and romantic private room     Deep tissue n soft relaxing full body massage     *  friendly n kindly      * open 7 day   10-10 pm      LILY< KATIE,  GiGi, Apple                           Poster's age: 28              Location:          Cerritos, East Pasadena, Acadia, El Monte, Long Beach, Palm Springs, San Gabriel, San Gabriel Valley            Post ID: 68499153 palmsprings          Other ads by this user:         *WE have many gorgeous n young ladies are waiting for you *Quite, clean and romantic private room Deep tissue n soft relaxing full body massage * friendly n kindly * open 7 day 10-10 pm LILY&lt; KATIE, GiGi, Apple Gorgeous young Asian Ladies guarantee 626-37169574 hands & B to B  Near Acadia 10 FWY - Palm Springs body rubs - backpage.com", 
    "12-5pm Transcend the bs & relax while you get healed! - 99 What is Reiki? Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy. 12-5pm Transcend the bs & relax while you get healed! - Louisville body rubs - backpage.com       Posted:      Saturday, June 18, 2016 2:00 PM                                                                         What is Reiki?      Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy.                           Poster's age: 99              Location:          Bardstown/Taylorsville Rd, Louisville            Post ID: 9231358 louisville          ", 
    "      Posted:      Tuesday, June 21, 2016 12:18 PM                                                                     Premium Reiki Experience at the SPA industrey SAFE* Clean* Private *NURU Studio*    2o2-330-3645                           Poster's age: 25              Location:          Kings Park Commack Northport Greenlawn, Long Beach, Long Island            Post ID: 77722372 longisland           Premium Reiki Experience at the SPA industrey SAFE* Clean* Private *NURU Studio* 2o2-330-3645 Clean Private Safe Nuru Studio Call for info NOW 202_33o_3645 - Long Island body rubs - backpage.com Clean Private Safe Nuru Studio Call for info NOW 202_33o_3645 - 25", 
    " SUN SPA - SPECIAL - $40 / 45 MINS - ASIAN MASSAGE SPLENDOR  - 24  SUN SPA - SPECIAL - $40 / 45 MINS - ASIAN MASSAGE SPLENDOR  - Denver body rubs - backpage.com                       Your browser does not support the videos.                        SUN ASIAN SPA   TEL : 3 0 3 - 9 3 6 - 0 3 2 8 Your Perfect Asian Get Away We Turn Massage Into Magic! The Best Relaxation Begins Here!  Deep Tissue - Swedish - Shiatsu Massage  Gorgeous Lovely Staff Luxurious Table Shower _______Click Here To Get Map_______  5220 West Mississippi Ave. Unit-D Lakewood, CO 80226   Open Daily: 9AM - 9PM / VISA/MC CARD ACCEPTED   This spa KNOWS how to take care of U! ", 
    "      Posted:      Tuesday, June 28, 2016 12:26 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Brookhaven, Glen Cove, Hempstead, Huntington, Islip, Long Island, North Hempstead, Oyster Bay, Smithtown, Sunrise Hwy / Route 27            Post ID: 81960557 longisland          Other ads by this user:         Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939  $40 Tasty Tuesday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - 21  $40 Tasty Tuesday Special !!Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - Long Island body rubs - backpage.com", 
    "Has encontrado el lugar donde se te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000!!!!  Con Kira  Masaje  % Ertico y Sensual    71857376  - Costa Rica anuncios clasificados erticos y para adultos - erticos - backpage.com       Publicado:      viernes, 24 de junio de 2016, 10:57 AM                                                                         Has encontrado el lugar donde se te dar el tiempo de realizarte un masaje relajante sensual sensitivo y ertico, estimulando tus sentidos al final cerrando con un orgasmo, ven y explora nuevos sentidos, de aqu el tantrico 1 hora 15000!!!!                           Edad de la persona que public el anuncio: 21              Ubicacin:          Heredia, MxM Hospital nuevo ***            Identificacin de la publicacin: 3132986 costarica          Otros anuncios de este usuario:          Con Kira  Masaje  % Ertico y Sensual    71857376  - 21", 
    "504-900-0462 36\" 22\" 36\" Ts Goodie Nuru GlideTs Goodie is ready to Touch your Body - 23       Posted:      Tuesday, July 12, 2016 12:17 PM                                                                         504-900-0462    36\" 22\" 36\"    Ts Goodie                           Poster's age: 23              Location:          Fayetteville            Post ID: 29696097 fayettevillenc           Nuru GlideTs Goodie is  ready to Touch your Body - Fayetteville body rubs - backpage.com", 
    "    search                             capetown                                                            freeclassifieds                                 Posted:      Friday, 1 July 2016, 18:44         Reply                                                                     you have tried the rest now ...experience the best with our 6 beautiful ladies.                           Poster's age: 20              Location:          Cape Town            Post ID: 7911009 capetown          Other ads by this user:               House of Nirvana - Sensual massages - 20 House of Nirvana - Sensual massages - Cape Town body rubs - backpage.com you have tried the rest now ...experience the best with our 6 beautiful ladies.", 
    "se habla espanolConvenient Locations Fort Lauderdale: 3925 N Andrews Avenue, 33309. Diagonal to Seven Eleven. Pompano  Hard Rock Casino Area: 5100 S State Road 7, Davie, Fl. Suites 5102, 5104, 5106 & 5124 Latinas SPARelaxing therapies, body scrub..       Posted:      Sunday, July 3, 2016 8:20 AM                                                                         se habla espanolConvenient Locations Fort Lauderdale: 3925 N Andrews Avenue, 33309.  Diagonal to Seven Eleven.  Pompano   Hard Rock Casino Area: 5100 S State Road 7, Davie, Fl. Suites 5102,  5104, 5106 & 5124 Latinas SPARelaxing therapies,  body scrub..                           Poster's age: 22              Location:          City of Ft. Lauderdale, Fort Lauderdale, Pompano Beach, Hollywoo, Ft Lauderdale            Post ID: 34080274 ftlauderdale          Other ads by this user:         Beautiful LatinasNew TherapistsWalk insEarly bird special Body Rub session 80 754 281 1279 - 22 Beautiful LatinasNew TherapistsWalk insEarly bird special Body Rub session 80 754 281 1279 - Fort Lauderdale body rubs - backpage.com", 
    "grand opening very young girl and nice bodyNew manger - Queens body rubs - backpage.com The best bodyru and nuru massage from our hottest Chinese 718-559-7060) grand opening very young girl and nice bodyNew manger - 23       Posted:      Tuesday, July 5, 2016 3:42 PM                The best bodyru and nuru massage from our hottest Chinese 718-559-7060)     Poster's age: 23              Location:          35th Ave & Prince St, Flushing, Flushing, Queens            Post ID: 61713007 queens          ", 
    "GENEVE Jeunes Coquines GFE 1ER JOUR  :-) - Genve massages - backpage.com GENEVE Jeunes Coquines GFE 1ER JOUR :-) - 18 Entre l'htel du Rhne et l'htel des Bergues, en face de la Banque HSBC +41 22 732 20 09 Chez nous vous trouvez toujours des jeunes, fraches et nouvelles coquines pour votre plus grand plaisir ... Zo & Lucy 18 ans, Jessy 20 ans N'hsitez pas  nous contacter bisousssss :- www.divageneva.ch                                                             Entre l'htel du Rhne et l'htel des Bergues, en face de la Banque HSBC    +41 22 732 20 09    Chez nous vous trouvez toujours des jeunes, fraches et nouvelles coquines pour votre plus grand plaisir  ... Zo & Lucy 18 ans, Jessy 20 ans   N'hsitez pas  nous contacter bisousssss :-    www.divageneva.ch     ge de lexpditeur: 18              Lieu:          Genve          ", 
    "Swedish  Deep Tissue  Oil MassageBody Slides Nuru  Quite, Clean, and Comfortable  Private Room Available for one Parking Lot Available  Full body massage  Every staff is friendly and kindly.  Provide a happy day for you. Real pic or you're free to walk away   OPEN 7 DAYS /11AM - 11PM  Foot Friendly  Role Play  Toys  Golden  631-526-9939  $40 Wacky Wednesday Special !Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - Long Island body rubs - backpage.com  $40 Wacky Wednesday Special !Grand Opening! Brazilian & Latina Bombshells Await!! Call Now $40  - 21       Posted:      Wednesday, July 6, 2016 3:46 PM                                                                         Swedish  Deep Tissue  Oil MassageBody Slides Nuru    Quite, Clean, and Comfortable   Private Room Available for one  Parking Lot Available   Full body massage   Every staff is friendly and kindly.   Provide a happy day for you.  Real pic or you're free to walk away    OPEN 7 DAYS /11AM - 11PM   Foot Friendly   Role Play  Toys  Golden    631-526-9939                           Poster's age: 21              Location:          Babylon, Hempstead, Huntington, Islip, Long Island, North Hempstead, Oyster Bay, sunrise Hwy / Route 27            Post ID: 82448997 longisland          Other ads by this user:        ", 
    "Long Island Dolls  Best nassau county studio What you see is what you Get - Long Island body rubs - backpage.com Long Island Dolls  Best nassau county studio What you see is what you Get - 21 50 short stay  70 extended stay  Young beautiful girls, 3 girls Daily  Clean, Discreet Studio, second floor office space No F\\S don't even ask Calls only l347-201-6592       Posted:      Tuesday, June 28, 2016 12:18 PM                                                                         50 short stay   70 extended stay     Young beautiful girls, 3 girls Daily     Clean, Discreet Studio, second floor office space     No F\\S don't even ask  Calls only l347-201-6592                           Poster's age: 21              Location:          109, wellwood, west bsbylon,, Babylon, Hempstead, Long Beach, Long Island, North Hempstead            Post ID: 74826866 longisland          ", 
    "      Posted:      Thursday, June 30, 2016 2:42 AM                                                                         24HrS  Body to Body Couples  Fetishes Unrushed Sessions  2-GIRL-Sessions Private Parking     Directions;South on Powerline right at Ihop then 1st left into shopping plaza suite 1415 next to Dunkin Donuts behind Checkers!!!                           Poster's age: 21              Location:          1415 South Powerline Road,Pompano, West Palm Beach            Post ID: 32553828 westpalmbeach           $ 50 ExotiC VixenS    SPA MAGIC   \"London\" & \"Candy\"  (954)793-7155 - 21 24HrS  Body to Body Couples  Fetishes Unrushed Sessions 2-GIRL-Sessions Private Parking Directions;South on Powerline right at Ihop then 1st left into shopping plaza suite 1415 next to Dunkin Donuts behind Checkers!!! $ 50 ExotiC VixenS    SPA MAGIC   \"London\" & \"Candy\"  (954)793-7155 - West Palm Beach body rubs - backpage.com", 
    "What is Reiki? Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy. Friday 65hh spcl - 99 Friday 65hh spcl - Louisville body rubs - backpage.com       Posted:      Friday, July 8, 2016 12:03 PM                                                                         What is Reiki?      Reiki is a Japanese technique for stress reduction and relaxation that also promotes healing. It is administered by \"laying on hands\" and is based on the idea that an unseen \"life force energy\" flows through us and is what causes us to be alive. If one's \"life force energy\" is low, then we are more likely to get sick or feel stress, and if it is high, we are more capable of being happy and healthy.                           Poster's age: 99              Location:          Bardstown/Taylorsville Rd, Louisville            Post ID: 9231358 louisville          ", 
    "Indulge Yourself in Pure Body Bliss With Michelle Relax your Body and your Mind  Great Special Massage  ShowerJacuzzi  732 2439987 2595 Woodbrige Avenue Edison 08817 Exotic Sensual  Brazilian Michelle 732 243 9987  - South Jersey body rubs - backpage.com       Posted:      Saturday, July 9, 2016 4:10 PM                                                                         Indulge Yourself in Pure Body Bliss With          Michelle         Relax your Body and your Mind   Great Special  Massage  ShowerJacuzzi  732 2439987         2595 Woodbrige Avenue Edison 08817                           Poster's age: 23              Location:          Central Jersey, Edison 2595 Woodbrige Avenue, Jersey Shore, North Jersey, South Jersey            Post ID: 29379593 southjersey          Other ads by this user:         Exotic Sensual  Brazilian Michelle 732 243 9987  - 23", 
    "The best online  for massage schooling for free.  Learn how to do body rubs, post body rub ads, do markeiting for your online business.  The number one body rub and massage resource online avaliable.  Rate providers and leave reviews   Error!   Only registered users are allowed to see this page     Massage and Bodyrub Independent Providers", 
    "      Posted:      Saturday, July 2, 2016 1:22 PM                ASIAN MASSAGE  Nice smoothing music in a calm enviroment will help you feel relaxed.      Give us a call & come experience one of the best massages of your life.      Masseuse has license   Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072  733 Tel: *262-765-9858   Open 7days a week, 9:00am to 10:00 pm    Beautiful professional Asian masseuse ,Will help you feel relaxed  Walk-ins, OK                           Poster's age: 24              Location:          21150 W Capitol Dr,#3,Brookfield, WI 530, La Crosse, Madison, Milwaukee, Sheboygan, Wausau            Post ID: 16205832 sheboygan           ASIAN MASSAGE Nice smoothing music in a calm enviroment will help you feel relaxed. Give us a call & come experience one of the best massages of your life. Masseuse has license Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072 733 Tel: *262-765-9858 Open 7days a week, 9:00am to 10:00 pm Beautiful professional Asian masseuse ,Will help you feel relaxed Walk-ins, OK    Free table shower *SOOTHING RELAXIN    Nurture Massage Spa 262-765-9858--- - Sheboygan body rubs - backpage.com    Free table shower *SOOTHING RELAXIN   Nurture Massage Spa 262-765-9858--- - 24", 
    "ASIAN MASSAGE Nice smoothing music in a calm enviroment will help you feel relaxed. Give us a call & come experience one of the best massages of your life. Masseuse has license Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072 733 Tel: *262-765-9858 Open 7days a week, 9:00am to 10:00 pm Beautiful professional Asian masseuse ,Will help you feel relaxed Walk-ins, OK    Free table shower *SOOTHING RELAXIN    Nurture Massage Spa 262-765-9858--- - Wausau body rubs - backpage.com       Posted:      Monday, June 20, 2016 1:16 PM                ASIAN MASSAGE  Nice smoothing music in a calm enviroment will help you feel relaxed.      Give us a call & come experience one of the best massages of your life.      Masseuse has license   Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072  733 Tel: *262-765-9858   Open 7days a week, 9:00am to 10:00 pm    Beautiful professional Asian masseuse ,Will help you feel relaxed  Walk-ins, OK                           Poster's age: 24              Location:          21150 W Capitol Dr,#3,Brookfield, WI 530, La Crosse, Madison, Milwaukee, Sheboygan, Wausau            Post ID: 16092852 wausau              Free table shower *SOOTHING RELAXIN   Nurture Massage Spa 262-765-9858--- - 24", 
    "      Posted:      Saturday, July 2, 2016 1:22 PM                ASIAN MASSAGE  Nice smoothing music in a calm enviroment will help you feel relaxed.      Give us a call & come experience one of the best massages of your life.      Masseuse has license   Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072  733 Tel: *262-765-9858   Open 7days a week, 9:00am to 10:00 pm    Beautiful professional Asian masseuse ,Will help you feel relaxed  Walk-ins, OK                           Poster's age: 24              Location:          21150 W Capitol Dr,#3,Brookfield, WI 530, La Crosse, Madison, Milwaukee, Sheboygan, Wausau            Post ID: 16205832 madison              Free table shower *SOOTHING RELAXIN    Nurture Massage Spa 262-765-9858--- - Madison body rubs - backpage.com ASIAN MASSAGE Nice smoothing music in a calm enviroment will help you feel relaxed. Give us a call & come experience one of the best massages of your life. Masseuse has license Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072 733 Tel: *262-765-9858 Open 7days a week, 9:00am to 10:00 pm Beautiful professional Asian masseuse ,Will help you feel relaxed Walk-ins, OK    Free table shower *SOOTHING RELAXIN   Nurture Massage Spa 262-765-9858--- - 24", 
    "      Posted:      Sunday, June 26, 2016 1:23 PM                ASIAN MASSAGE  Nice smoothing music in a calm enviroment will help you feel relaxed.      Give us a call & come experience one of the best massages of your life.      Masseuse has license   Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072  733 Tel: *262-765-9858   Open 7days a week, 9:00am to 10:00 pm    Beautiful professional Asian masseuse ,Will help you feel relaxed  Walk-ins, OK                           Poster's age: 24              Location:          21150 W Capitol Dr,#3,Brookfield, WI 530, La Crosse, Madison, Milwaukee, Sheboygan, Wausau            Post ID: 16149778 wisconsin              Free table shower *SOOTHING RELAXIN    Nurture Massage Spa 262-765-9858--- - Wisconsin body rubs - backpage.com ASIAN MASSAGE Nice smoothing music in a calm enviroment will help you feel relaxed. Give us a call & come experience one of the best massages of your life. Masseuse has license Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072 733 Tel: *262-765-9858 Open 7days a week, 9:00am to 10:00 pm Beautiful professional Asian masseuse ,Will help you feel relaxed Walk-ins, OK    Free table shower *SOOTHING RELAXIN   Nurture Massage Spa 262-765-9858--- - 24", 
    "      Posted:      Wednesday, June 22, 2016 1:08 PM                ASIAN MASSAGE  Nice smoothing music in a calm enviroment will help you feel relaxed.      Give us a call & come experience one of the best massages of your life.      Masseuse has license   Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072  733 Tel: *262-765-9858   Open 7days a week, 9:00am to 10:00 pm    Beautiful professional Asian masseuse ,Will help you feel relaxed  Walk-ins, OK                           Poster's age: 24              Location:          21150 W Capitol Dr,#3,Brookfield, WI 530, La Crosse, Madison, Milwaukee, Sheboygan, Wausau            Post ID: 16110433 wausau           ASIAN MASSAGE Nice smoothing music in a calm enviroment will help you feel relaxed. Give us a call & come experience one of the best massages of your life. Masseuse has license Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072 733 Tel: *262-765-9858 Open 7days a week, 9:00am to 10:00 pm Beautiful professional Asian masseuse ,Will help you feel relaxed Walk-ins, OK    Free table shower *SOOTHING RELAXIN    Nurture Massage Spa 262-765-9858--- - Wausau body rubs - backpage.com    Free table shower *SOOTHING RELAXIN   Nurture Massage Spa 262-765-9858--- - 24", 
    "      Posted:      Friday, June 24, 2016 1:41 PM                ASIAN MASSAGE  Nice smoothing music in a calm enviroment will help you feel relaxed.      Give us a call & come experience one of the best massages of your life.      Masseuse has license   Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072  733 Tel: *262-765-9858   Open 7days a week, 9:00am to 10:00 pm    Beautiful professional Asian masseuse ,Will help you feel relaxed  Walk-ins, OK                           Poster's age: 24              Location:          21150 W Capitol Dr,#3,Brookfield, WI 530, La Crosse, Madison, Milwaukee, Sheboygan, Wausau            Post ID: 16130118 wisconsin              Free table shower *SOOTHING RELAXIN    Nurture Massage Spa 262-765-9858--- - Wisconsin body rubs - backpage.com ASIAN MASSAGE Nice smoothing music in a calm enviroment will help you feel relaxed. Give us a call & come experience one of the best massages of your life. Masseuse has license Address: 21150 W Capitol Dr,#3,Brookfield, WI 53072 733 Tel: *262-765-9858 Open 7days a week, 9:00am to 10:00 pm Beautiful professional Asian masseuse ,Will help you feel relaxed Walk-ins, OK    Free table shower *SOOTHING RELAXIN   Nurture Massage Spa 262-765-9858--- - 24"
    ]
    import json
    for content in contents:
        # content = ''
        node = Node(content)
        print json.dumps(node._features, indent=4)
        # print node._vector

